version: '3.4'

services:
  app:
    image: node:10.20-jessie-slim
    ports:
      - "7771:7777"
    volumes:
      - ./sick-fits/frontend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  server:
    image: node:10.20-jessie-slim
    ports:
     - "4441:4444"
    volumes:
     - ./sick-fits/backend:/usr/src/app
     - /usr/src/app/node_modules
    environment:
      FRONTEND_URL: http://localhost:7777
      PRISMA_ENDPOINT: http://localhost:4466
      PRISMA_SECRET: supersecretprisma
      APP_SECRET: jwtsecret123
      STRIPE_SECRET: sk_123youchangethis
      PORT: 4444
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: db
            user: root
            password: 123456
            rawAccess: true
            port: 3306
            migrations: true
  db:
    image: mysql:5.7.30
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
volumes:
  db-data:
